# Generated by Django 4.2.5 on 2024-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseMain', '0010_delete_category_delete_source_userdetail_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
